# Generated by Django 4.1.4 on 2022-12-16 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=25)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin', to='rareapi.rareuser')),
                ('modified_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modified_user', to='rareapi.rareuser')),
                ('second_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_admin', to='rareapi.rareuser')),
            ],
        ),
    ]
