# Generated by Django 4.1.4 on 2022-12-21 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0002_alter_post_image_url_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post_id',
            new_name='post',
        ),
    ]
